"use client";

import * as React from "react";
import QRCode from "qrcode";

/**
 * QR-code renderer. Server-renders to an inline SVG string (no canvas, no
 * external image fetch) so the secret never leaves the user's browser. We
 * call the encoder client-side because the otpauth URL is generated by an
 * authenticated API call and shouldn't traverse a cache.
 */
export function QrCode({
  value,
  size = 192,
  className,
  ariaLabel = "Scan with your authenticator app",
}: {
  value: string;
  size?: number;
  className?: string;
  ariaLabel?: string;
}) {
  const [svg, setSvg] = React.useState<string | null>(null);
  const [error, setError] = React.useState<string | null>(null);

  React.useEffect(() => {
    let cancelled = false;
    QRCode.toString(value, {
      type: "svg",
      errorCorrectionLevel: "M",
      margin: 1,
      width: size,
      color: { dark: "#1A1A1A", light: "#FFFFFF" },
    })
      .then((s) => {
        if (!cancelled) setSvg(s);
      })
      .catch((err) => {
        if (!cancelled) setError(err instanceof Error ? err.message : "QR render failed");
      });
    return () => {
      cancelled = true;
    };
  }, [value, size]);

  if (error) {
    return (
      <div
        role="img"
        aria-label="QR code unavailable"
        className={`grid place-items-center rounded-md border border-border bg-canvas-banded p-4 text-caption text-ink-tertiary ${className ?? ""}`}
        style={{ width: size, height: size }}
      >
        QR unavailable. Use the secret below.
      </div>
    );
  }
  if (!svg) {
    return (
      <div
        aria-hidden
        className={`animate-pulse rounded-md bg-canvas-banded ${className ?? ""}`}
        style={{ width: size, height: size }}
      />
    );
  }
  return (
    <div
      role="img"
      aria-label={ariaLabel}
      className={`inline-block rounded-md border border-border bg-white p-2 ${className ?? ""}`}
      // eslint-disable-next-line react/no-danger
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  );
}
